server:
  name: "mpc-signer"
  address:     ":8000"
  workId: 1
  cpuCore: 2
  privateKey: "0ac7d64995c6b4daac2688c0e40d25af50887ada5b7a4cbe197ada0bdef32375"
  hasRisk:  true

jaegerUrl: ""

logger:
  level : "all"
  stdout: true 
  rotateExpire: "1d"
  path: "./"

database:
  default:
  - link: "pgsql:postgres:123456@tcp(172.22.104.148:10100)/mpc"

cache:
  sessionDuration: 2000

nrpc:
  natsUrl: "172.22.104.148:4222"

# redis 
redis:
  default:
    address: 172.22.104.148:6379
    db:      1
  cache:
    address:     172.22.104.148:6379
    db:          2

userToken: "https://auth-dev.mixmarvel-sdk.com/info"
# ?token=xxxxxxxxx
etcd:
  address: "172.22.104.148:2379"
  riskRpc: "riskRpc"


gfcli:
  gen:
    dao:
    - link:     "pgsql:postgres:123456@tcp(172.22.104.148:10100)/mpc"
      tables:   "mpc_context"
      jsonCase: "CamelLower"
