base: li17server
server:
  address:     ":8000"
  workId: 1
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

cache:
# redis mem
  type: "redis"
  duration: 100
  redis:
    Addr: "127.0.0.1:6379"
    Db: 1




