base: li17server
server:
  address:     ":8000"
  workId: 1

logger:
  level : "all"
  stdout: false 
  rotateExpire: "1d"
  path: "./"

database:
  default:
  - link: "pgsql:postgres:123456@tcp(127.0.0.1:10100)/riskcontrol"

cache:
  sessionDur: 10000
  contextDur: 0
# redis mem
  type: "redis"
  redis:
    Addr: "127.0.0.1:6379"
    Db: 1
etcd:
  address: "127.0.0.1:2379"

sms:
  huawei:
    APIAddress: "https://smsapi.cn-south-1.myhuaweicloud.com:443/sms/batchSendSms/v1"
    ApplicationKey: "DZcZWoIauKdHY1wD0179m4Jk5N9V"
    ApplicationSecret: "1GSPX8WyCwJbTfwEohqsBlOzbcam"
    Sender: "cs106900001477"
    TemplateID: "4ea904bd91ad47b690573aa6be183952"
    Signature: "华为云测试签名"

emailOTP:
  Mail: "xinwei.li@mixmarvel.com"
  Password: "Kkj7pJAdUpLpjgYE"
  Host: "smtp.exmail.qq.com"
  Port: 465
  Subject: "Subject"
  Body: "Body"

gfcli:
  gen:
    dao:
    - link:     "pgsql:postgres:123456@tcp(127.0.0.1:10100)/riskcontrol"
      tables:   "contract_abi"
      jsonCase: "CamelLower"
