base: li17server
server:
  address:     ":8000"
  workId: 1
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

cache:
  sessionDur: 100
  contextDur: 0
# redis mem
  type: "redis"
  redis:
    Addr: "127.0.0.1:6379"
    Db: 1




