// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sign

import (
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/crypto"
)

func randPrivateKey() string {
	pk, _ := crypto.GenerateKey()
	pkBytes := crypto.FromECDSA(pk)
	pkstr := hexutil.Encode(pkBytes)[2:]
	return pkstr
}
