// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mpcServer/internal/dao/internal"
)

// internalMpcContextDao is internal type for wrapping internal DAO implements.
type internalMpcContextDao = *internal.MpcContextDao

// mpcContextDao is the data access object for table mpc_context.
// You can define custom methods on it to extend its functionality as you wish.
type mpcContextDao struct {
	internalMpcContextDao
}

var (
	// MpcContext is globally public accessible object for table mpc_context operations.
	MpcContext = mpcContextDao{
		internal.NewMpcContextDao(),
	}
)

// Fill with you ideas below.
